# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and deploy to Heroku

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@master

      - name: Heroku login to container registry
        env: 
          HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME_DEVEL}}
        run: heroku container:login

      - name: Heroku push
        env: 
          HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME_DEVEL}}
        run: heroku container:push --app $HEROKU_APP_NAME_DEVEL worker

      - name: Heroku release
        env: 
          HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME_DEVEL}}
        run: heroku container:release --app $HEROKU_APP_NAME_DEVEL worker
